// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA5GrW3TNLI00L9ozjdO_TX71-NV3qA4s',
    appId: '1:454194038459:web:9f989c85feff14493d0b9e',
    messagingSenderId: '454194038459',
    projectId: 'tapart-c309d',
    authDomain: 'tapart-c309d.firebaseapp.com',
    storageBucket: 'tapart-c309d.firebasestorage.app',
    measurementId: 'G-ZYZ6YFS1DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvY8a4k18bbhLyGY1zTzbuU7--9TgTTI8',
    appId: '1:454194038459:android:28a77ba3d771df113d0b9e',
    messagingSenderId: '454194038459',
    projectId: 'tapart-c309d',
    storageBucket: 'tapart-c309d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3vcA92l76sW9KlbW92TsKpCS9L85FJlY',
    appId: '1:454194038459:ios:3ee770b717c5e4c43d0b9e',
    messagingSenderId: '454194038459',
    projectId: 'tapart-c309d',
    storageBucket: 'tapart-c309d.firebasestorage.app',
    iosBundleId: 'com.example.prelimproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3vcA92l76sW9KlbW92TsKpCS9L85FJlY',
    appId: '1:454194038459:ios:3ee770b717c5e4c43d0b9e',
    messagingSenderId: '454194038459',
    projectId: 'tapart-c309d',
    storageBucket: 'tapart-c309d.firebasestorage.app',
    iosBundleId: 'com.example.prelimproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA5GrW3TNLI00L9ozjdO_TX71-NV3qA4s',
    appId: '1:454194038459:web:48611320162f33153d0b9e',
    messagingSenderId: '454194038459',
    projectId: 'tapart-c309d',
    authDomain: 'tapart-c309d.firebaseapp.com',
    storageBucket: 'tapart-c309d.firebasestorage.app',
    measurementId: 'G-M2GQ66NVQJ',
  );

}